version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    command: npm run start:dev
    depends_on:
      - redis
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './client:/usr/src/app/client'
      - '/usr/src/app/client/node_modules'
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - server

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: 'redis:alpine'
    command: redis-server
    ports:
      - 6379:6379
